services:
  web:
    container_name: web
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    command: [ "uvicorn", "main:app", "--reload", "--host", "0.0.0.0", "--port", "8000"]
    networks:
      - search-nw

  search:
    container_name: search
    image: searxng/searxng
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - ./searxng:/etc/searxng
    environment:
      - BASE_URL=http://localhost:8080/
      - INSTANCE_NAME=news
    networks:
      - search-nw

networks:
  search-nw:
    driver: bridge
